server:
  port: 8089

spring:
  application.name: Product-01
  datasource:
    url: jdbc:postgresql://localhost:5432/product_01
    username: postgres
    password: root
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true


